### ISSUE TITLE
Error: newline in string found at line 

### ISSUE THREAD

**Issue by brandonguigo** [chaaz/versio#24]
**Describe the bug**
I have setup the versio-prev tag with the following versions
```
{"versions":{"1":"1.0.2","2":"1.0.0", "3":"1.0.4", "4":"1.0.4", "5":"1.0.1", "6":"1.0.0"}}
```
Then, when i do versio check, it's says : 
```
Error: newline in string found at line 2 column 59
```
.versio.yaml
````
options:
  prev_tag: "versio-prev"
projects:
  - name: "common"
    root: "common"
    id: 1
    tag_prefix: "common"
    tag_prefix_separator: "/"
    labels: npm
    version:
      file: "package.json"
      json: "version"
  - name: "core-seed"
    root: "core-api/mongo-seed"
    id: 2
    tag_prefix: "core-seed"
    tag_prefix_separator: "/"
    labels: npm
    version:
      file: "package.json"
      json: "version"
  - name: "core"
    root: "core-api"
    id: 3
    tag_prefix: "core"
    tag_prefix_separator: "/"
    labels: npm
    version:
      file: "package.json"
      json: "version"
  - name: "core-service-migration"
    root: "core-api/migrate-mongo"
    id: 4
    tag_prefix: "core-migration"
    tag_prefix_separator: "/"
    labels: npm
    version:
      file: "package.json"
      json: "version"
  - name: "pdf"
    root: "pdf-api"
    id: 5
    tag_prefix: "pdf"
    tag_prefix_separator: "/"
    labels: npm
    version:
      file: "package.json"
      json: "version"
  - name: "solal-common-api"
    root: "common-api"
    id: 6
    tag_prefix: "common-api"
    tag_prefix_separator: "/"
    labels: npm
    version:
      file: "package.json"
      json: "version"
sizes:
  use_angular: true
  fail: ["*"]
```
**To Reproduce**
Run `RUST_LOG=versio=trace RUST_BACKTRACE=full versio check`

**Expected behavior**
It should check as expected
